# GENERATED by tools/gen_julia.py from schema/pandoc-ast.json
# (pandoc-api-version 1.23.1.2). Do not edit; regenerate instead.

const PANDOC_API_VERSION = (1, 23, 1, 2)

"pandoc's `QuoteType`."
@enum QuoteType SingleQuote DoubleQuote

"pandoc's `MathType`."
@enum MathType DisplayMath InlineMath

"pandoc's `ListNumberStyle`."
@enum ListNumberStyle DefaultStyle Example Decimal LowerRoman UpperRoman LowerAlpha UpperAlpha

"pandoc's `ListNumberDelim`."
@enum ListNumberDelim DefaultDelim Period OneParen TwoParens

"pandoc's `Alignment`."
@enum Alignment AlignLeft AlignRight AlignCenter AlignDefault

"pandoc's `CitationMode`."
@enum CitationMode AuthorInText SuppressAuthor NormalCitation

"Any of pandoc's `Block` constructors."
abstract type Block <: Node end

"Any of pandoc's `MetaValue` constructors."
abstract type MetaValue <: Node end

"Any of pandoc's `Inline` constructors."
abstract type Inline <: Node end

"Any of pandoc's `ColWidth` constructors."
abstract type ColWidthBase <: Node end

"pandoc's `Meta`."
const Meta = Dict{String, MetaValue}

"pandoc's `Format`."
const Format = String

"pandoc's `ShortCaption`."
const ShortCaption = Vector{Inline}

"pandoc's `RowHeadColumns`."
const RowHeadColumns = Int

"pandoc's `RowSpan`."
const RowSpan = Int

"pandoc's `ColSpan`."
const ColSpan = Int

"pandoc's `Pandoc`."
mutable struct Pandoc <: Node
    meta::Meta
    blocks::Vector{Block}
    Pandoc(meta::AbstractDict, blocks::AbstractVector) = new(meta, blocks)
end
_encoding(::Type{Pandoc}) = :root
_keys(::Type{Pandoc}) = ("meta", "blocks",)
function Pandoc(blocks::Union{Block, AbstractString}...; meta = Dict{String, MetaValue}())
    Pandoc(meta, _variadic(Block, blocks))
end
function Pandoc(blocks::AbstractVector; meta = Dict{String, MetaValue}())
    Pandoc(meta, _variadic(Block, blocks))
end

"pandoc's `Plain`, a `Block`."
mutable struct Plain <: Block
    content::Vector{Inline}
    Plain(content::AbstractVector) = new(content)
end
_encoding(::Type{Plain}) = :value
function Plain(content::Union{Inline, AbstractString}...)
    Plain(_variadic(Inline, content))
end

"pandoc's `Para`, a `Block`."
mutable struct Para <: Block
    content::Vector{Inline}
    Para(content::AbstractVector) = new(content)
end
_encoding(::Type{Para}) = :value
function Para(content::Union{Inline, AbstractString}...)
    Para(_variadic(Inline, content))
end

"pandoc's `LineBlock`, a `Block`."
mutable struct LineBlock <: Block
    content::Vector{Vector{Inline}}
    LineBlock(content::AbstractVector) = new(content)
end
_encoding(::Type{LineBlock}) = :value
function LineBlock(content::Union{AbstractVector, AbstractString}...)
    LineBlock(_variadic(Vector{Inline}, content))
end

"pandoc's `RawBlock`, a `Block`."
mutable struct RawBlock <: Block
    format::Format
    text::String
    RawBlock(format, text) = new(format, text)
end
_encoding(::Type{RawBlock}) = :array

"pandoc's `BlockQuote`, a `Block`."
mutable struct BlockQuote <: Block
    content::Vector{Block}
    BlockQuote(content::AbstractVector) = new(content)
end
_encoding(::Type{BlockQuote}) = :value
function BlockQuote(content::Union{Block, AbstractString}...)
    BlockQuote(_variadic(Block, content))
end

"pandoc's `BulletList`, a `Block`."
mutable struct BulletList <: Block
    content::Vector{Vector{Block}}
    BulletList(content::AbstractVector) = new(content)
end
_encoding(::Type{BulletList}) = :value
function BulletList(content::Union{AbstractVector, AbstractString}...)
    BulletList(_variadic(Vector{Block}, content))
end

"pandoc's `DefinitionList`, a `Block`."
mutable struct DefinitionList <: Block
    content::Vector{Tuple{Vector{Inline}, Vector{Vector{Block}}}}
    DefinitionList(content::AbstractVector) = new(content)
end
_encoding(::Type{DefinitionList}) = :value
function DefinitionList(content::Tuple{Vector{Inline}, Vector{Vector{Block}}}...)
    DefinitionList(_variadic(Tuple{Vector{Inline}, Vector{Vector{Block}}}, content))
end

"pandoc's `HorizontalRule`, a `Block`."
mutable struct HorizontalRule <: Block
end
_encoding(::Type{HorizontalRule}) = :none

"pandoc's `MetaMap`, a `MetaValue`."
mutable struct MetaMap <: MetaValue
    content::Dict{String, MetaValue}
    MetaMap(content::AbstractDict) = new(content)
end
_encoding(::Type{MetaMap}) = :value
function MetaMap(; content = Dict{String, MetaValue}())
    MetaMap(content)
end

"pandoc's `MetaList`, a `MetaValue`."
mutable struct MetaList <: MetaValue
    content::Vector{MetaValue}
    MetaList(content::AbstractVector) = new(content)
end
_encoding(::Type{MetaList}) = :value
function MetaList(content::MetaValue...)
    MetaList(_variadic(MetaValue, content))
end

"pandoc's `MetaBool`, a `MetaValue`."
mutable struct MetaBool <: MetaValue
    value::Bool
    MetaBool(value) = new(value)
end
_encoding(::Type{MetaBool}) = :value

"pandoc's `MetaString`, a `MetaValue`."
mutable struct MetaString <: MetaValue
    text::String
    MetaString(text) = new(text)
end
_encoding(::Type{MetaString}) = :value

"pandoc's `MetaInlines`, a `MetaValue`."
mutable struct MetaInlines <: MetaValue
    content::Vector{Inline}
    MetaInlines(content::AbstractVector) = new(content)
end
_encoding(::Type{MetaInlines}) = :value
function MetaInlines(content::Union{Inline, AbstractString}...)
    MetaInlines(_variadic(Inline, content))
end

"pandoc's `MetaBlocks`, a `MetaValue`."
mutable struct MetaBlocks <: MetaValue
    content::Vector{Block}
    MetaBlocks(content::AbstractVector) = new(content)
end
_encoding(::Type{MetaBlocks}) = :value
function MetaBlocks(content::Union{Block, AbstractString}...)
    MetaBlocks(_variadic(Block, content))
end

"pandoc's `Str`, a `Inline`."
mutable struct Str <: Inline
    text::String
    Str(text) = new(text)
end
_encoding(::Type{Str}) = :value

"pandoc's `Emph`, a `Inline`."
mutable struct Emph <: Inline
    content::Vector{Inline}
    Emph(content::AbstractVector) = new(content)
end
_encoding(::Type{Emph}) = :value
function Emph(content::Union{Inline, AbstractString}...)
    Emph(_variadic(Inline, content))
end

"pandoc's `Underline`, a `Inline`."
mutable struct Underline <: Inline
    content::Vector{Inline}
    Underline(content::AbstractVector) = new(content)
end
_encoding(::Type{Underline}) = :value
function Underline(content::Union{Inline, AbstractString}...)
    Underline(_variadic(Inline, content))
end

"pandoc's `Strong`, a `Inline`."
mutable struct Strong <: Inline
    content::Vector{Inline}
    Strong(content::AbstractVector) = new(content)
end
_encoding(::Type{Strong}) = :value
function Strong(content::Union{Inline, AbstractString}...)
    Strong(_variadic(Inline, content))
end

"pandoc's `Strikeout`, a `Inline`."
mutable struct Strikeout <: Inline
    content::Vector{Inline}
    Strikeout(content::AbstractVector) = new(content)
end
_encoding(::Type{Strikeout}) = :value
function Strikeout(content::Union{Inline, AbstractString}...)
    Strikeout(_variadic(Inline, content))
end

"pandoc's `Superscript`, a `Inline`."
mutable struct Superscript <: Inline
    content::Vector{Inline}
    Superscript(content::AbstractVector) = new(content)
end
_encoding(::Type{Superscript}) = :value
function Superscript(content::Union{Inline, AbstractString}...)
    Superscript(_variadic(Inline, content))
end

"pandoc's `Subscript`, a `Inline`."
mutable struct Subscript <: Inline
    content::Vector{Inline}
    Subscript(content::AbstractVector) = new(content)
end
_encoding(::Type{Subscript}) = :value
function Subscript(content::Union{Inline, AbstractString}...)
    Subscript(_variadic(Inline, content))
end

"pandoc's `SmallCaps`, a `Inline`."
mutable struct SmallCaps <: Inline
    content::Vector{Inline}
    SmallCaps(content::AbstractVector) = new(content)
end
_encoding(::Type{SmallCaps}) = :value
function SmallCaps(content::Union{Inline, AbstractString}...)
    SmallCaps(_variadic(Inline, content))
end

"pandoc's `Quoted`, a `Inline`."
mutable struct Quoted <: Inline
    quote_type::QuoteType
    content::Vector{Inline}
    Quoted(quote_type, content::AbstractVector) = new(quote_type, content)
end
_encoding(::Type{Quoted}) = :array
function Quoted(quote_type, content::Union{Inline, AbstractString}...)
    Quoted(quote_type, _variadic(Inline, content))
end

"pandoc's `Space`, a `Inline`."
mutable struct Space <: Inline
end
_encoding(::Type{Space}) = :none

"pandoc's `SoftBreak`, a `Inline`."
mutable struct SoftBreak <: Inline
end
_encoding(::Type{SoftBreak}) = :none

"pandoc's `LineBreak`, a `Inline`."
mutable struct LineBreak <: Inline
end
_encoding(::Type{LineBreak}) = :none

"pandoc's `Math`, a `Inline`."
mutable struct Math <: Inline
    math_type::MathType
    text::String
    Math(math_type, text) = new(math_type, text)
end
_encoding(::Type{Math}) = :array

"pandoc's `RawInline`, a `Inline`."
mutable struct RawInline <: Inline
    format::Format
    text::String
    RawInline(format, text) = new(format, text)
end
_encoding(::Type{RawInline}) = :array

"pandoc's `Note`, a `Inline`."
mutable struct Note <: Inline
    content::Vector{Block}
    Note(content::AbstractVector) = new(content)
end
_encoding(::Type{Note}) = :value
function Note(content::Union{Block, AbstractString}...)
    Note(_variadic(Block, content))
end

"pandoc's `Attr`."
mutable struct Attr <: Node
    identifier::String
    classes::Vector{String}
    attributes::Vector{Tuple{String, String}}
    Attr(identifier, classes::AbstractVector, attributes::AbstractVector) = new(identifier, classes, attributes)
end
_encoding(::Type{Attr}) = :array
function Attr(; identifier = "", classes = String[], attributes = Tuple{String, String}[])
    Attr(identifier, classes, attributes)
end

"pandoc's `ListAttributes`."
mutable struct ListAttributes <: Node
    start::Int
    style::ListNumberStyle
    delimiter::ListNumberDelim
    ListAttributes(start, style, delimiter) = new(start, style, delimiter)
end
_encoding(::Type{ListAttributes}) = :array
function ListAttributes(; start = 1, style = DefaultStyle, delimiter = DefaultDelim)
    ListAttributes(start, style, delimiter)
end

"pandoc's `Caption`."
mutable struct Caption <: Node
    short::Union{Nothing, ShortCaption}
    content::Vector{Block}
    Caption(short, content::AbstractVector) = new(short, content)
end
_encoding(::Type{Caption}) = :array
function Caption(content::Union{Block, AbstractString}...; short = nothing)
    Caption(short, _variadic(Block, content))
end
function Caption(content::AbstractVector; short = nothing)
    Caption(short, _variadic(Block, content))
end

"pandoc's `ColSpec`."
mutable struct ColSpec <: Node
    alignment::Alignment
    width::ColWidthBase
    ColSpec(alignment, width) = new(alignment, width)
end
_encoding(::Type{ColSpec}) = :array
function ColSpec(; alignment = AlignDefault, width = ColWidthDefault())
    ColSpec(alignment, width)
end

"pandoc's `Citation`."
mutable struct Citation <: Node
    id::String
    prefix::Vector{Inline}
    suffix::Vector{Inline}
    mode::CitationMode
    note_num::Int
    hash::Int
    Citation(id, prefix::AbstractVector, suffix::AbstractVector, mode, note_num, hash) = new(id, prefix, suffix, mode, note_num, hash)
end
_encoding(::Type{Citation}) = :object
_keys(::Type{Citation}) = ("citationId", "citationPrefix", "citationSuffix", "citationMode", "citationNoteNum", "citationHash",)
function Citation(id; prefix = Inline[], suffix = Inline[], mode = NormalCitation, note_num = 0, hash = 0)
    Citation(id, prefix, suffix, mode, note_num, hash)
end

"pandoc's `Target`."
mutable struct Target <: Node
    url::String
    title::String
    Target(url, title) = new(url, title)
end
_encoding(::Type{Target}) = :array
function Target(url; title = "")
    Target(url, title)
end

"pandoc's `ColWidth`, a `ColWidth`."
mutable struct ColWidth <: ColWidthBase
    width::Float64
    ColWidth(width) = new(width)
end
_encoding(::Type{ColWidth}) = :value

"pandoc's `ColWidthDefault`, a `ColWidth`."
mutable struct ColWidthDefault <: ColWidthBase
end
_encoding(::Type{ColWidthDefault}) = :none

"pandoc's `Cell`."
mutable struct Cell <: Node
    attr::Attr
    alignment::Alignment
    row_span::RowSpan
    col_span::ColSpan
    content::Vector{Block}
    Cell(attr::Attr, alignment, row_span, col_span, content::AbstractVector) = new(attr, alignment, row_span, col_span, content)
end
_encoding(::Type{Cell}) = :array
function Cell(content::Union{Block, AbstractString}...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], alignment = AlignDefault, row_span = 1, col_span = 1)
    __attr = _flat(Attr, attr, :Cell, :attr; identifier, classes, attributes)
    Cell(__attr, alignment, row_span, col_span, _variadic(Block, content))
end
function Cell(content::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], alignment = AlignDefault, row_span = 1, col_span = 1)
    __attr = _flat(Attr, attr, :Cell, :attr; identifier, classes, attributes)
    Cell(__attr, alignment, row_span, col_span, _variadic(Block, content))
end

"pandoc's `CodeBlock`, a `Block`."
mutable struct CodeBlock <: Block
    attr::Attr
    text::String
    CodeBlock(attr::Attr, text) = new(attr, text)
end
_encoding(::Type{CodeBlock}) = :array
function CodeBlock(text; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :CodeBlock, :attr; identifier, classes, attributes)
    CodeBlock(__attr, text)
end

"pandoc's `OrderedList`, a `Block`."
mutable struct OrderedList <: Block
    list_attributes::ListAttributes
    content::Vector{Vector{Block}}
    OrderedList(list_attributes::ListAttributes, content::AbstractVector) = new(list_attributes, content)
end
_encoding(::Type{OrderedList}) = :array
function OrderedList(content::Union{AbstractVector, AbstractString}...; list_attributes::Union{Nothing, ListAttributes} = nothing, start = 1, style = DefaultStyle, delimiter = DefaultDelim)
    __list_attributes = _flat(ListAttributes, list_attributes, :OrderedList, :list_attributes; start, style, delimiter)
    OrderedList(__list_attributes, _variadic(Vector{Block}, content))
end

"pandoc's `Header`, a `Block`."
mutable struct Header <: Block
    level::Int
    attr::Attr
    content::Vector{Inline}
    Header(level, attr::Attr, content::AbstractVector) = new(level, attr, content)
end
_encoding(::Type{Header}) = :array
function Header(level, content::Union{Inline, AbstractString}...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Header, :attr; identifier, classes, attributes)
    Header(level, __attr, _variadic(Inline, content))
end
function Header(level, content::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Header, :attr; identifier, classes, attributes)
    Header(level, __attr, _variadic(Inline, content))
end

"pandoc's `Figure`, a `Block`."
mutable struct Figure <: Block
    attr::Attr
    caption::Caption
    content::Vector{Block}
    Figure(attr::Attr, caption::Caption, content::AbstractVector) = new(attr, caption, content)
end
_encoding(::Type{Figure}) = :array
function Figure(content::Union{Block, AbstractString}...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], caption = Caption())
    __attr = _flat(Attr, attr, :Figure, :attr; identifier, classes, attributes)
    Figure(__attr, caption, _variadic(Block, content))
end
function Figure(content::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], caption = Caption())
    __attr = _flat(Attr, attr, :Figure, :attr; identifier, classes, attributes)
    Figure(__attr, caption, _variadic(Block, content))
end

"pandoc's `Div`, a `Block`."
mutable struct Div <: Block
    attr::Attr
    content::Vector{Block}
    Div(attr::Attr, content::AbstractVector) = new(attr, content)
end
_encoding(::Type{Div}) = :array
function Div(content::Union{Block, AbstractString}...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Div, :attr; identifier, classes, attributes)
    Div(__attr, _variadic(Block, content))
end
function Div(content::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Div, :attr; identifier, classes, attributes)
    Div(__attr, _variadic(Block, content))
end

"pandoc's `Cite`, a `Inline`."
mutable struct Cite <: Inline
    citations::Vector{Citation}
    content::Vector{Inline}
    Cite(citations::AbstractVector, content::AbstractVector) = new(citations, content)
end
_encoding(::Type{Cite}) = :array
function Cite(; citations = Citation[], content = Inline[])
    Cite(citations, content)
end

"pandoc's `Code`, a `Inline`."
mutable struct Code <: Inline
    attr::Attr
    text::String
    Code(attr::Attr, text) = new(attr, text)
end
_encoding(::Type{Code}) = :array
function Code(text; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Code, :attr; identifier, classes, attributes)
    Code(__attr, text)
end

"pandoc's `Link`, a `Inline`."
mutable struct Link <: Inline
    attr::Attr
    content::Vector{Inline}
    target::Target
    Link(attr::Attr, content::AbstractVector, target::Target) = new(attr, content, target)
end
_encoding(::Type{Link}) = :array
function Link(content::Union{Inline, AbstractString}...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], target::Union{Nothing, Target} = nothing, url = nothing, title = "")
    __attr = _flat(Attr, attr, :Link, :attr; identifier, classes, attributes)
    __target = _flat(Target, target, :Link, :target; url, title)
    Link(__attr, _variadic(Inline, content), __target)
end
function Link(content::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], target::Union{Nothing, Target} = nothing, url = nothing, title = "")
    __attr = _flat(Attr, attr, :Link, :attr; identifier, classes, attributes)
    __target = _flat(Target, target, :Link, :target; url, title)
    Link(__attr, _variadic(Inline, content), __target)
end

"pandoc's `Image`, a `Inline`."
mutable struct Image <: Inline
    attr::Attr
    content::Vector{Inline}
    target::Target
    Image(attr::Attr, content::AbstractVector, target::Target) = new(attr, content, target)
end
_encoding(::Type{Image}) = :array
function Image(content::Union{Inline, AbstractString}...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], target::Union{Nothing, Target} = nothing, url = nothing, title = "")
    __attr = _flat(Attr, attr, :Image, :attr; identifier, classes, attributes)
    __target = _flat(Target, target, :Image, :target; url, title)
    Image(__attr, _variadic(Inline, content), __target)
end
function Image(content::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], target::Union{Nothing, Target} = nothing, url = nothing, title = "")
    __attr = _flat(Attr, attr, :Image, :attr; identifier, classes, attributes)
    __target = _flat(Target, target, :Image, :target; url, title)
    Image(__attr, _variadic(Inline, content), __target)
end

"pandoc's `Span`, a `Inline`."
mutable struct Span <: Inline
    attr::Attr
    content::Vector{Inline}
    Span(attr::Attr, content::AbstractVector) = new(attr, content)
end
_encoding(::Type{Span}) = :array
function Span(content::Union{Inline, AbstractString}...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Span, :attr; identifier, classes, attributes)
    Span(__attr, _variadic(Inline, content))
end
function Span(content::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Span, :attr; identifier, classes, attributes)
    Span(__attr, _variadic(Inline, content))
end

"pandoc's `Row`."
mutable struct Row <: Node
    attr::Attr
    cells::Vector{Cell}
    Row(attr::Attr, cells::AbstractVector) = new(attr, cells)
end
_encoding(::Type{Row}) = :array
function Row(cells::Cell...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Row, :attr; identifier, classes, attributes)
    Row(__attr, _variadic(Cell, cells))
end
function Row(cells::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :Row, :attr; identifier, classes, attributes)
    Row(__attr, _variadic(Cell, cells))
end

"pandoc's `TableHead`."
mutable struct TableHead <: Node
    attr::Attr
    rows::Vector{Row}
    TableHead(attr::Attr, rows::AbstractVector) = new(attr, rows)
end
_encoding(::Type{TableHead}) = :array
function TableHead(rows::Row...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :TableHead, :attr; identifier, classes, attributes)
    TableHead(__attr, _variadic(Row, rows))
end
function TableHead(rows::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :TableHead, :attr; identifier, classes, attributes)
    TableHead(__attr, _variadic(Row, rows))
end

"pandoc's `TableBody`."
mutable struct TableBody <: Node
    attr::Attr
    row_head_columns::RowHeadColumns
    head::Vector{Row}
    body::Vector{Row}
    TableBody(attr::Attr, row_head_columns, head::AbstractVector, body::AbstractVector) = new(attr, row_head_columns, head, body)
end
_encoding(::Type{TableBody}) = :array
function TableBody(; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], row_head_columns = 0, head = Row[], body = Row[])
    __attr = _flat(Attr, attr, :TableBody, :attr; identifier, classes, attributes)
    TableBody(__attr, row_head_columns, head, body)
end

"pandoc's `TableFoot`."
mutable struct TableFoot <: Node
    attr::Attr
    rows::Vector{Row}
    TableFoot(attr::Attr, rows::AbstractVector) = new(attr, rows)
end
_encoding(::Type{TableFoot}) = :array
function TableFoot(rows::Row...; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :TableFoot, :attr; identifier, classes, attributes)
    TableFoot(__attr, _variadic(Row, rows))
end
function TableFoot(rows::AbstractVector; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[])
    __attr = _flat(Attr, attr, :TableFoot, :attr; identifier, classes, attributes)
    TableFoot(__attr, _variadic(Row, rows))
end

"pandoc's `Table`, a `Block`."
mutable struct Table <: Block
    attr::Attr
    caption::Caption
    col_specs::Vector{ColSpec}
    head::TableHead
    bodies::Vector{TableBody}
    foot::TableFoot
    Table(attr::Attr, caption::Caption, col_specs::AbstractVector, head::TableHead, bodies::AbstractVector, foot::TableFoot) = new(attr, caption, col_specs, head, bodies, foot)
end
_encoding(::Type{Table}) = :array
function Table(; attr::Union{Nothing, Attr} = nothing, identifier = "", classes = String[], attributes = Tuple{String, String}[], caption = Caption(), col_specs = ColSpec[], head = TableHead(), bodies = TableBody[], foot = TableFoot())
    __attr = _flat(Attr, attr, :Table, :attr; identifier, classes, attributes)
    Table(__attr, caption, col_specs, head, bodies, foot)
end

# how each type is encoded, for core.jl
_constructors(::Type{Block}) = (Plain, Para, LineBlock, CodeBlock, RawBlock, BlockQuote, OrderedList, BulletList, DefinitionList, Header, HorizontalRule, Table, Figure, Div,)
_constructors(::Type{MetaValue}) = (MetaMap, MetaList, MetaBool, MetaString, MetaInlines, MetaBlocks,)
_constructors(::Type{Inline}) = (Str, Emph, Underline, Strong, Strikeout, Superscript, Subscript, SmallCaps, Quoted, Cite, Code, Space, SoftBreak, LineBreak, Math, RawInline, Link, Image, Note, Span,)
_constructors(::Type{ColWidthBase}) = (ColWidth, ColWidthDefault,)
const _SUMS = (Block, MetaValue, Inline, ColWidthBase,)
const _ENUMS = (QuoteType, MathType, ListNumberStyle, ListNumberDelim, Alignment, CitationMode,)

export PANDOC_API_VERSION, Pandoc, Meta, Block, Plain, Para, LineBlock, CodeBlock, RawBlock, BlockQuote, OrderedList, BulletList, DefinitionList, Header, HorizontalRule, Table, Figure, Div, MetaValue, MetaMap, MetaList, MetaBool, MetaString, MetaInlines, MetaBlocks, Inline, Str, Emph, Underline, Strong, Strikeout, Superscript, Subscript, SmallCaps, Quoted, Cite, Code, Space, SoftBreak, LineBreak, Math, RawInline, Link, Image, Note, Span, Attr, Format, ListAttributes, Caption, ColSpec, TableHead, TableBody, TableFoot, QuoteType, SingleQuote, DoubleQuote, Citation, MathType, DisplayMath, InlineMath, Target, ListNumberStyle, DefaultStyle, Example, Decimal, LowerRoman, UpperRoman, LowerAlpha, UpperAlpha, ListNumberDelim, DefaultDelim, Period, OneParen, TwoParens, ShortCaption, Alignment, AlignLeft, AlignRight, AlignCenter, AlignDefault, ColWidthBase, ColWidth, ColWidthDefault, Row, RowHeadColumns, CitationMode, AuthorInText, SuppressAuthor, NormalCitation, Cell, RowSpan, ColSpan
