// GENERATED by tools/gen_rust.py from schema/pandoc-ast.json
// (pandoc-api-version 1.23.1.2). Do not edit; regenerate instead.

//! pandoc's AST types, their JSON encoding, and `VisitMut`.

#![allow(clippy::all)]

use serde::de;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::collections::BTreeMap;

/// The pandoc-types API version these types are for.
pub const PANDOC_API_VERSION: [i64; 4] = [1, 23, 1, 2];

/// pandoc's `Pandoc`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Pandoc {
    #[serde(rename = "pandoc-api-version")]
    pub api_version: Vec<i64>,
    pub meta: Meta,
    pub blocks: Vec<Block>,
}

impl Default for Pandoc {
    fn default() -> Self {
        Pandoc {
            api_version: PANDOC_API_VERSION.to_vec(),
            meta: BTreeMap::new(),
            blocks: Vec::new(),
        }
    }
}

/// pandoc's `Meta`.
pub type Meta = BTreeMap<String, MetaValue>;

/// pandoc's `Block`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "t", content = "c")]
pub enum Block {
    Plain(Vec<Inline>),
    Para(Vec<Inline>),
    LineBlock(Vec<Vec<Inline>>),
    CodeBlock(CodeBlock),
    RawBlock(RawBlock),
    BlockQuote(Vec<Block>),
    OrderedList(OrderedList),
    BulletList(Vec<Vec<Block>>),
    DefinitionList(Vec<(Vec<Inline>, Vec<Vec<Block>>)>),
    Header(Header),
    HorizontalRule,
    Table(Table),
    Figure(Figure),
    Div(Div),
}

impl<'de> Deserialize<'de> for Block {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &[
            "Plain",
            "Para",
            "LineBlock",
            "CodeBlock",
            "RawBlock",
            "BlockQuote",
            "OrderedList",
            "BulletList",
            "DefinitionList",
            "Header",
            "HorizontalRule",
            "Table",
            "Figure",
            "Div",
        ];
        struct V;
        impl<'de> de::Visitor<'de> for V {
            type Value = Block;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("a Block: {\"t\": ..., \"c\": ...}")
            }
            fn visit_map<A: de::MapAccess<'de>>(self, mut map: A) -> Result<Block, A::Error> {
                let mut tag: Option<String> = None;
                let mut value: Option<Block> = None;
                let mut early: Option<serde_json::Value> = None;
                while let Some(key) = map.next_key::<String>()? {
                    if key == "t" {
                        let t: String = map.next_value()?;
                        if !TAGS.contains(&t.as_str()) {
                            return Err(de::Error::unknown_variant(&t, TAGS));
                        }
                        value = match early.take() {
                            Some(c) => Some(from_value(&t, c)?),
                            None => unit(&t),
                        };
                        tag = Some(t);
                    } else if key == "c" {
                        match tag.as_deref() {
                            None => early = Some(map.next_value()?),
                            Some(t) => {
                                value = Some(match t {
                                    "Plain" => Block::Plain(map.next_value()?),
                                    "Para" => Block::Para(map.next_value()?),
                                    "LineBlock" => Block::LineBlock(map.next_value()?),
                                    "CodeBlock" => Block::CodeBlock(map.next_value()?),
                                    "RawBlock" => Block::RawBlock(map.next_value()?),
                                    "BlockQuote" => Block::BlockQuote(map.next_value()?),
                                    "OrderedList" => Block::OrderedList(map.next_value()?),
                                    "BulletList" => Block::BulletList(map.next_value()?),
                                    "DefinitionList" => Block::DefinitionList(map.next_value()?),
                                    "Header" => Block::Header(map.next_value()?),
                                    "HorizontalRule" => {
                                        map.next_value::<de::IgnoredAny>()?;
                                        Block::HorizontalRule
                                    }
                                    "Table" => Block::Table(map.next_value()?),
                                    "Figure" => Block::Figure(map.next_value()?),
                                    "Div" => Block::Div(map.next_value()?),
                                    _ => unreachable!(),
                                })
                            }
                        }
                    } else {
                        map.next_value::<de::IgnoredAny>()?;
                    }
                }
                match (tag, value) {
                    (_, Some(v)) => Ok(v),
                    (None, _) => Err(de::Error::missing_field("t")),
                    (Some(_), None) => Err(de::Error::missing_field("c")),
                }
            }
        }
        // "c" before "t" (not pandoc's order): decode it once "t" is known
        fn from_value<E: de::Error>(t: &str, c: serde_json::Value) -> Result<Block, E> {
            fn json<T: de::DeserializeOwned, E: de::Error>(c: serde_json::Value) -> Result<T, E> {
                serde_path_to_error::deserialize(c).map_err(|e| {
                    let p = e.path().to_string();
                    let at = match p.as_str() {
                        "." => "c".to_string(),
                        p if p.starts_with('[') => format!("c{p}"),
                        p => format!("c.{p}"),
                    };
                    E::custom(format!("{at}: {}", e.inner()))
                })
            }
            Ok(match t {
                "Plain" => Block::Plain(json(c)?),
                "Para" => Block::Para(json(c)?),
                "LineBlock" => Block::LineBlock(json(c)?),
                "CodeBlock" => Block::CodeBlock(json(c)?),
                "RawBlock" => Block::RawBlock(json(c)?),
                "BlockQuote" => Block::BlockQuote(json(c)?),
                "OrderedList" => Block::OrderedList(json(c)?),
                "BulletList" => Block::BulletList(json(c)?),
                "DefinitionList" => Block::DefinitionList(json(c)?),
                "Header" => Block::Header(json(c)?),
                "HorizontalRule" => Block::HorizontalRule,
                "Table" => Block::Table(json(c)?),
                "Figure" => Block::Figure(json(c)?),
                "Div" => Block::Div(json(c)?),
                _ => unreachable!(),
            })
        }
        fn unit(t: &str) -> Option<Block> {
            match t {
                "HorizontalRule" => Some(Block::HorizontalRule),
                _ => None,
            }
        }
        d.deserialize_map(V)
    }
}

/// pandoc's `CodeBlock`, a `Block`.
#[derive(Debug, Clone, PartialEq)]
pub struct CodeBlock {
    pub attr: Attr,
    pub text: String,
}

impl Serialize for CodeBlock {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.text).serialize(s)
    }
}

impl<'de> Deserialize<'de> for CodeBlock {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, text) = <(Attr, String)>::deserialize(d)?;
        Ok(CodeBlock { attr, text })
    }
}

/// pandoc's `RawBlock`, a `Block`.
#[derive(Debug, Clone, PartialEq)]
pub struct RawBlock {
    pub format: Format,
    pub text: String,
}

impl Serialize for RawBlock {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.format, &self.text).serialize(s)
    }
}

impl<'de> Deserialize<'de> for RawBlock {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (format, text) = <(Format, String)>::deserialize(d)?;
        Ok(RawBlock { format, text })
    }
}

/// pandoc's `OrderedList`, a `Block`.
#[derive(Debug, Clone, PartialEq)]
pub struct OrderedList {
    pub list_attributes: ListAttributes,
    pub content: Vec<Vec<Block>>,
}

impl Default for OrderedList {
    fn default() -> Self {
        OrderedList {
            list_attributes: ListAttributes::default(),
            content: Vec::new(),
        }
    }
}

impl Serialize for OrderedList {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.list_attributes, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for OrderedList {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (list_attributes, content) = <(ListAttributes, Vec<Vec<Block>>)>::deserialize(d)?;
        Ok(OrderedList {
            list_attributes,
            content,
        })
    }
}

/// pandoc's `Header`, a `Block`.
#[derive(Debug, Clone, PartialEq)]
pub struct Header {
    pub level: i64,
    pub attr: Attr,
    pub content: Vec<Inline>,
}

impl Serialize for Header {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.level, &self.attr, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Header {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (level, attr, content) = <(i64, Attr, Vec<Inline>)>::deserialize(d)?;
        Ok(Header {
            level,
            attr,
            content,
        })
    }
}

/// pandoc's `Table`, a `Block`.
#[derive(Debug, Clone, PartialEq)]
pub struct Table {
    pub attr: Attr,
    pub caption: Caption,
    pub col_specs: Vec<ColSpec>,
    pub head: TableHead,
    pub bodies: Vec<TableBody>,
    pub foot: TableFoot,
}

impl Default for Table {
    fn default() -> Self {
        Table {
            attr: Attr::default(),
            caption: Caption::default(),
            col_specs: Vec::new(),
            head: TableHead::default(),
            bodies: Vec::new(),
            foot: TableFoot::default(),
        }
    }
}

impl Serialize for Table {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (
            &self.attr,
            &self.caption,
            &self.col_specs,
            &self.head,
            &self.bodies,
            &self.foot,
        )
            .serialize(s)
    }
}

impl<'de> Deserialize<'de> for Table {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, caption, col_specs, head, bodies, foot) = <(
            Attr,
            Caption,
            Vec<ColSpec>,
            TableHead,
            Vec<TableBody>,
            TableFoot,
        )>::deserialize(d)?;
        Ok(Table {
            attr,
            caption,
            col_specs,
            head,
            bodies,
            foot,
        })
    }
}

/// pandoc's `Figure`, a `Block`.
#[derive(Debug, Clone, PartialEq)]
pub struct Figure {
    pub attr: Attr,
    pub caption: Caption,
    pub content: Vec<Block>,
}

impl Default for Figure {
    fn default() -> Self {
        Figure {
            attr: Attr::default(),
            caption: Caption::default(),
            content: Vec::new(),
        }
    }
}

impl Serialize for Figure {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.caption, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Figure {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, caption, content) = <(Attr, Caption, Vec<Block>)>::deserialize(d)?;
        Ok(Figure {
            attr,
            caption,
            content,
        })
    }
}

/// pandoc's `Div`, a `Block`.
#[derive(Debug, Clone, PartialEq)]
pub struct Div {
    pub attr: Attr,
    pub content: Vec<Block>,
}

impl Default for Div {
    fn default() -> Self {
        Div {
            attr: Attr::default(),
            content: Vec::new(),
        }
    }
}

impl Serialize for Div {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Div {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, content) = <(Attr, Vec<Block>)>::deserialize(d)?;
        Ok(Div { attr, content })
    }
}

/// pandoc's `MetaValue`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "t", content = "c")]
pub enum MetaValue {
    MetaMap(BTreeMap<String, MetaValue>),
    MetaList(Vec<MetaValue>),
    MetaBool(bool),
    MetaString(String),
    MetaInlines(Vec<Inline>),
    MetaBlocks(Vec<Block>),
}

impl<'de> Deserialize<'de> for MetaValue {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &[
            "MetaMap",
            "MetaList",
            "MetaBool",
            "MetaString",
            "MetaInlines",
            "MetaBlocks",
        ];
        struct V;
        impl<'de> de::Visitor<'de> for V {
            type Value = MetaValue;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("a MetaValue: {\"t\": ..., \"c\": ...}")
            }
            fn visit_map<A: de::MapAccess<'de>>(self, mut map: A) -> Result<MetaValue, A::Error> {
                let mut tag: Option<String> = None;
                let mut value: Option<MetaValue> = None;
                let mut early: Option<serde_json::Value> = None;
                while let Some(key) = map.next_key::<String>()? {
                    if key == "t" {
                        let t: String = map.next_value()?;
                        if !TAGS.contains(&t.as_str()) {
                            return Err(de::Error::unknown_variant(&t, TAGS));
                        }
                        value = match early.take() {
                            Some(c) => Some(from_value(&t, c)?),
                            None => unit(&t),
                        };
                        tag = Some(t);
                    } else if key == "c" {
                        match tag.as_deref() {
                            None => early = Some(map.next_value()?),
                            Some(t) => {
                                value = Some(match t {
                                    "MetaMap" => MetaValue::MetaMap(map.next_value()?),
                                    "MetaList" => MetaValue::MetaList(map.next_value()?),
                                    "MetaBool" => MetaValue::MetaBool(map.next_value()?),
                                    "MetaString" => MetaValue::MetaString(map.next_value()?),
                                    "MetaInlines" => MetaValue::MetaInlines(map.next_value()?),
                                    "MetaBlocks" => MetaValue::MetaBlocks(map.next_value()?),
                                    _ => unreachable!(),
                                })
                            }
                        }
                    } else {
                        map.next_value::<de::IgnoredAny>()?;
                    }
                }
                match (tag, value) {
                    (_, Some(v)) => Ok(v),
                    (None, _) => Err(de::Error::missing_field("t")),
                    (Some(_), None) => Err(de::Error::missing_field("c")),
                }
            }
        }
        // "c" before "t" (not pandoc's order): decode it once "t" is known
        fn from_value<E: de::Error>(t: &str, c: serde_json::Value) -> Result<MetaValue, E> {
            fn json<T: de::DeserializeOwned, E: de::Error>(c: serde_json::Value) -> Result<T, E> {
                serde_path_to_error::deserialize(c).map_err(|e| {
                    let p = e.path().to_string();
                    let at = match p.as_str() {
                        "." => "c".to_string(),
                        p if p.starts_with('[') => format!("c{p}"),
                        p => format!("c.{p}"),
                    };
                    E::custom(format!("{at}: {}", e.inner()))
                })
            }
            Ok(match t {
                "MetaMap" => MetaValue::MetaMap(json(c)?),
                "MetaList" => MetaValue::MetaList(json(c)?),
                "MetaBool" => MetaValue::MetaBool(json(c)?),
                "MetaString" => MetaValue::MetaString(json(c)?),
                "MetaInlines" => MetaValue::MetaInlines(json(c)?),
                "MetaBlocks" => MetaValue::MetaBlocks(json(c)?),
                _ => unreachable!(),
            })
        }
        fn unit(t: &str) -> Option<MetaValue> {
            match t {
                _ => None,
            }
        }
        d.deserialize_map(V)
    }
}

/// pandoc's `Inline`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "t", content = "c")]
pub enum Inline {
    Str(String),
    Emph(Vec<Inline>),
    Underline(Vec<Inline>),
    Strong(Vec<Inline>),
    Strikeout(Vec<Inline>),
    Superscript(Vec<Inline>),
    Subscript(Vec<Inline>),
    SmallCaps(Vec<Inline>),
    Quoted(Quoted),
    Cite(Cite),
    Code(Code),
    Space,
    SoftBreak,
    LineBreak,
    Math(Math),
    RawInline(RawInline),
    Link(Link),
    Image(Image),
    Note(Vec<Block>),
    Span(Span),
}

impl<'de> Deserialize<'de> for Inline {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &[
            "Str",
            "Emph",
            "Underline",
            "Strong",
            "Strikeout",
            "Superscript",
            "Subscript",
            "SmallCaps",
            "Quoted",
            "Cite",
            "Code",
            "Space",
            "SoftBreak",
            "LineBreak",
            "Math",
            "RawInline",
            "Link",
            "Image",
            "Note",
            "Span",
        ];
        struct V;
        impl<'de> de::Visitor<'de> for V {
            type Value = Inline;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("a Inline: {\"t\": ..., \"c\": ...}")
            }
            fn visit_map<A: de::MapAccess<'de>>(self, mut map: A) -> Result<Inline, A::Error> {
                let mut tag: Option<String> = None;
                let mut value: Option<Inline> = None;
                let mut early: Option<serde_json::Value> = None;
                while let Some(key) = map.next_key::<String>()? {
                    if key == "t" {
                        let t: String = map.next_value()?;
                        if !TAGS.contains(&t.as_str()) {
                            return Err(de::Error::unknown_variant(&t, TAGS));
                        }
                        value = match early.take() {
                            Some(c) => Some(from_value(&t, c)?),
                            None => unit(&t),
                        };
                        tag = Some(t);
                    } else if key == "c" {
                        match tag.as_deref() {
                            None => early = Some(map.next_value()?),
                            Some(t) => {
                                value = Some(match t {
                                    "Str" => Inline::Str(map.next_value()?),
                                    "Emph" => Inline::Emph(map.next_value()?),
                                    "Underline" => Inline::Underline(map.next_value()?),
                                    "Strong" => Inline::Strong(map.next_value()?),
                                    "Strikeout" => Inline::Strikeout(map.next_value()?),
                                    "Superscript" => Inline::Superscript(map.next_value()?),
                                    "Subscript" => Inline::Subscript(map.next_value()?),
                                    "SmallCaps" => Inline::SmallCaps(map.next_value()?),
                                    "Quoted" => Inline::Quoted(map.next_value()?),
                                    "Cite" => Inline::Cite(map.next_value()?),
                                    "Code" => Inline::Code(map.next_value()?),
                                    "Space" => {
                                        map.next_value::<de::IgnoredAny>()?;
                                        Inline::Space
                                    }
                                    "SoftBreak" => {
                                        map.next_value::<de::IgnoredAny>()?;
                                        Inline::SoftBreak
                                    }
                                    "LineBreak" => {
                                        map.next_value::<de::IgnoredAny>()?;
                                        Inline::LineBreak
                                    }
                                    "Math" => Inline::Math(map.next_value()?),
                                    "RawInline" => Inline::RawInline(map.next_value()?),
                                    "Link" => Inline::Link(map.next_value()?),
                                    "Image" => Inline::Image(map.next_value()?),
                                    "Note" => Inline::Note(map.next_value()?),
                                    "Span" => Inline::Span(map.next_value()?),
                                    _ => unreachable!(),
                                })
                            }
                        }
                    } else {
                        map.next_value::<de::IgnoredAny>()?;
                    }
                }
                match (tag, value) {
                    (_, Some(v)) => Ok(v),
                    (None, _) => Err(de::Error::missing_field("t")),
                    (Some(_), None) => Err(de::Error::missing_field("c")),
                }
            }
        }
        // "c" before "t" (not pandoc's order): decode it once "t" is known
        fn from_value<E: de::Error>(t: &str, c: serde_json::Value) -> Result<Inline, E> {
            fn json<T: de::DeserializeOwned, E: de::Error>(c: serde_json::Value) -> Result<T, E> {
                serde_path_to_error::deserialize(c).map_err(|e| {
                    let p = e.path().to_string();
                    let at = match p.as_str() {
                        "." => "c".to_string(),
                        p if p.starts_with('[') => format!("c{p}"),
                        p => format!("c.{p}"),
                    };
                    E::custom(format!("{at}: {}", e.inner()))
                })
            }
            Ok(match t {
                "Str" => Inline::Str(json(c)?),
                "Emph" => Inline::Emph(json(c)?),
                "Underline" => Inline::Underline(json(c)?),
                "Strong" => Inline::Strong(json(c)?),
                "Strikeout" => Inline::Strikeout(json(c)?),
                "Superscript" => Inline::Superscript(json(c)?),
                "Subscript" => Inline::Subscript(json(c)?),
                "SmallCaps" => Inline::SmallCaps(json(c)?),
                "Quoted" => Inline::Quoted(json(c)?),
                "Cite" => Inline::Cite(json(c)?),
                "Code" => Inline::Code(json(c)?),
                "Space" => Inline::Space,
                "SoftBreak" => Inline::SoftBreak,
                "LineBreak" => Inline::LineBreak,
                "Math" => Inline::Math(json(c)?),
                "RawInline" => Inline::RawInline(json(c)?),
                "Link" => Inline::Link(json(c)?),
                "Image" => Inline::Image(json(c)?),
                "Note" => Inline::Note(json(c)?),
                "Span" => Inline::Span(json(c)?),
                _ => unreachable!(),
            })
        }
        fn unit(t: &str) -> Option<Inline> {
            match t {
                "Space" => Some(Inline::Space),
                "SoftBreak" => Some(Inline::SoftBreak),
                "LineBreak" => Some(Inline::LineBreak),
                _ => None,
            }
        }
        d.deserialize_map(V)
    }
}

/// pandoc's `Quoted`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct Quoted {
    pub quote_type: QuoteType,
    pub content: Vec<Inline>,
}

impl Serialize for Quoted {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.quote_type, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Quoted {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (quote_type, content) = <(QuoteType, Vec<Inline>)>::deserialize(d)?;
        Ok(Quoted {
            quote_type,
            content,
        })
    }
}

/// pandoc's `Cite`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct Cite {
    pub citations: Vec<Citation>,
    pub content: Vec<Inline>,
}

impl Default for Cite {
    fn default() -> Self {
        Cite {
            citations: Vec::new(),
            content: Vec::new(),
        }
    }
}

impl Serialize for Cite {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.citations, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Cite {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (citations, content) = <(Vec<Citation>, Vec<Inline>)>::deserialize(d)?;
        Ok(Cite { citations, content })
    }
}

/// pandoc's `Code`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct Code {
    pub attr: Attr,
    pub text: String,
}

impl Serialize for Code {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.text).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Code {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, text) = <(Attr, String)>::deserialize(d)?;
        Ok(Code { attr, text })
    }
}

/// pandoc's `Math`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct Math {
    pub math_type: MathType,
    pub text: String,
}

impl Serialize for Math {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.math_type, &self.text).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Math {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (math_type, text) = <(MathType, String)>::deserialize(d)?;
        Ok(Math { math_type, text })
    }
}

/// pandoc's `RawInline`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct RawInline {
    pub format: Format,
    pub text: String,
}

impl Serialize for RawInline {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.format, &self.text).serialize(s)
    }
}

impl<'de> Deserialize<'de> for RawInline {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (format, text) = <(Format, String)>::deserialize(d)?;
        Ok(RawInline { format, text })
    }
}

/// pandoc's `Link`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct Link {
    pub attr: Attr,
    pub content: Vec<Inline>,
    pub target: Target,
}

impl Serialize for Link {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.content, &self.target).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Link {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, content, target) = <(Attr, Vec<Inline>, Target)>::deserialize(d)?;
        Ok(Link {
            attr,
            content,
            target,
        })
    }
}

/// pandoc's `Image`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct Image {
    pub attr: Attr,
    pub content: Vec<Inline>,
    pub target: Target,
}

impl Serialize for Image {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.content, &self.target).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Image {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, content, target) = <(Attr, Vec<Inline>, Target)>::deserialize(d)?;
        Ok(Image {
            attr,
            content,
            target,
        })
    }
}

/// pandoc's `Span`, a `Inline`.
#[derive(Debug, Clone, PartialEq)]
pub struct Span {
    pub attr: Attr,
    pub content: Vec<Inline>,
}

impl Default for Span {
    fn default() -> Self {
        Span {
            attr: Attr::default(),
            content: Vec::new(),
        }
    }
}

impl Serialize for Span {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Span {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, content) = <(Attr, Vec<Inline>)>::deserialize(d)?;
        Ok(Span { attr, content })
    }
}

/// pandoc's `Attr`.
#[derive(Debug, Clone, PartialEq)]
pub struct Attr {
    pub identifier: String,
    pub classes: Vec<String>,
    pub attributes: Vec<(String, String)>,
}

impl Default for Attr {
    fn default() -> Self {
        Attr {
            identifier: String::new(),
            classes: Vec::new(),
            attributes: Vec::new(),
        }
    }
}

impl Serialize for Attr {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.identifier, &self.classes, &self.attributes).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Attr {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (identifier, classes, attributes) =
            <(String, Vec<String>, Vec<(String, String)>)>::deserialize(d)?;
        Ok(Attr {
            identifier,
            classes,
            attributes,
        })
    }
}

/// pandoc's `Format`.
pub type Format = String;

/// pandoc's `ListAttributes`.
#[derive(Debug, Clone, PartialEq)]
pub struct ListAttributes {
    pub start: i64,
    pub style: ListNumberStyle,
    pub delimiter: ListNumberDelim,
}

impl Default for ListAttributes {
    fn default() -> Self {
        ListAttributes {
            start: 1,
            style: ListNumberStyle::DefaultStyle,
            delimiter: ListNumberDelim::DefaultDelim,
        }
    }
}

impl Serialize for ListAttributes {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.start, &self.style, &self.delimiter).serialize(s)
    }
}

impl<'de> Deserialize<'de> for ListAttributes {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (start, style, delimiter) = <(i64, ListNumberStyle, ListNumberDelim)>::deserialize(d)?;
        Ok(ListAttributes {
            start,
            style,
            delimiter,
        })
    }
}

/// pandoc's `Caption`.
#[derive(Debug, Clone, PartialEq)]
pub struct Caption {
    pub short: Option<ShortCaption>,
    pub content: Vec<Block>,
}

impl Default for Caption {
    fn default() -> Self {
        Caption {
            short: None,
            content: Vec::new(),
        }
    }
}

impl Serialize for Caption {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.short, &self.content).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Caption {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (short, content) = <(Option<ShortCaption>, Vec<Block>)>::deserialize(d)?;
        Ok(Caption { short, content })
    }
}

/// pandoc's `ColSpec`.
#[derive(Debug, Clone, PartialEq)]
pub struct ColSpec {
    pub alignment: Alignment,
    pub width: ColWidth,
}

impl Default for ColSpec {
    fn default() -> Self {
        ColSpec {
            alignment: Alignment::AlignDefault,
            width: ColWidth::ColWidthDefault,
        }
    }
}

impl Serialize for ColSpec {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.alignment, &self.width).serialize(s)
    }
}

impl<'de> Deserialize<'de> for ColSpec {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (alignment, width) = <(Alignment, ColWidth)>::deserialize(d)?;
        Ok(ColSpec { alignment, width })
    }
}

/// pandoc's `TableHead`.
#[derive(Debug, Clone, PartialEq)]
pub struct TableHead {
    pub attr: Attr,
    pub rows: Vec<Row>,
}

impl Default for TableHead {
    fn default() -> Self {
        TableHead {
            attr: Attr::default(),
            rows: Vec::new(),
        }
    }
}

impl Serialize for TableHead {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.rows).serialize(s)
    }
}

impl<'de> Deserialize<'de> for TableHead {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, rows) = <(Attr, Vec<Row>)>::deserialize(d)?;
        Ok(TableHead { attr, rows })
    }
}

/// pandoc's `TableBody`.
#[derive(Debug, Clone, PartialEq)]
pub struct TableBody {
    pub attr: Attr,
    pub row_head_columns: RowHeadColumns,
    pub head: Vec<Row>,
    pub body: Vec<Row>,
}

impl Default for TableBody {
    fn default() -> Self {
        TableBody {
            attr: Attr::default(),
            row_head_columns: 0,
            head: Vec::new(),
            body: Vec::new(),
        }
    }
}

impl Serialize for TableBody {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.row_head_columns, &self.head, &self.body).serialize(s)
    }
}

impl<'de> Deserialize<'de> for TableBody {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, row_head_columns, head, body) =
            <(Attr, RowHeadColumns, Vec<Row>, Vec<Row>)>::deserialize(d)?;
        Ok(TableBody {
            attr,
            row_head_columns,
            head,
            body,
        })
    }
}

/// pandoc's `TableFoot`.
#[derive(Debug, Clone, PartialEq)]
pub struct TableFoot {
    pub attr: Attr,
    pub rows: Vec<Row>,
}

impl Default for TableFoot {
    fn default() -> Self {
        TableFoot {
            attr: Attr::default(),
            rows: Vec::new(),
        }
    }
}

impl Serialize for TableFoot {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.rows).serialize(s)
    }
}

impl<'de> Deserialize<'de> for TableFoot {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, rows) = <(Attr, Vec<Row>)>::deserialize(d)?;
        Ok(TableFoot { attr, rows })
    }
}

/// pandoc's `QuoteType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(tag = "t")]
pub enum QuoteType {
    SingleQuote,
    DoubleQuote,
}

impl<'de> Deserialize<'de> for QuoteType {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &["SingleQuote", "DoubleQuote"];
        let t = crate::de_tag(d, "QuoteType", TAGS)?;
        Ok(match t.as_str() {
            "SingleQuote" => QuoteType::SingleQuote,
            "DoubleQuote" => QuoteType::DoubleQuote,
            _ => unreachable!(),
        })
    }
}

/// pandoc's `Citation`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Citation {
    #[serde(rename = "citationId")]
    pub id: String,
    #[serde(rename = "citationPrefix")]
    pub prefix: Vec<Inline>,
    #[serde(rename = "citationSuffix")]
    pub suffix: Vec<Inline>,
    #[serde(rename = "citationMode")]
    pub mode: CitationMode,
    #[serde(rename = "citationNoteNum")]
    pub note_num: i64,
    #[serde(rename = "citationHash")]
    pub hash: i64,
}

/// pandoc's `MathType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(tag = "t")]
pub enum MathType {
    DisplayMath,
    InlineMath,
}

impl<'de> Deserialize<'de> for MathType {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &["DisplayMath", "InlineMath"];
        let t = crate::de_tag(d, "MathType", TAGS)?;
        Ok(match t.as_str() {
            "DisplayMath" => MathType::DisplayMath,
            "InlineMath" => MathType::InlineMath,
            _ => unreachable!(),
        })
    }
}

/// pandoc's `Target`.
#[derive(Debug, Clone, PartialEq)]
pub struct Target {
    pub url: String,
    pub title: String,
}

impl Serialize for Target {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.url, &self.title).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Target {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (url, title) = <(String, String)>::deserialize(d)?;
        Ok(Target { url, title })
    }
}

/// pandoc's `ListNumberStyle`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(tag = "t")]
pub enum ListNumberStyle {
    DefaultStyle,
    Example,
    Decimal,
    LowerRoman,
    UpperRoman,
    LowerAlpha,
    UpperAlpha,
}

impl<'de> Deserialize<'de> for ListNumberStyle {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &[
            "DefaultStyle",
            "Example",
            "Decimal",
            "LowerRoman",
            "UpperRoman",
            "LowerAlpha",
            "UpperAlpha",
        ];
        let t = crate::de_tag(d, "ListNumberStyle", TAGS)?;
        Ok(match t.as_str() {
            "DefaultStyle" => ListNumberStyle::DefaultStyle,
            "Example" => ListNumberStyle::Example,
            "Decimal" => ListNumberStyle::Decimal,
            "LowerRoman" => ListNumberStyle::LowerRoman,
            "UpperRoman" => ListNumberStyle::UpperRoman,
            "LowerAlpha" => ListNumberStyle::LowerAlpha,
            "UpperAlpha" => ListNumberStyle::UpperAlpha,
            _ => unreachable!(),
        })
    }
}

/// pandoc's `ListNumberDelim`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(tag = "t")]
pub enum ListNumberDelim {
    DefaultDelim,
    Period,
    OneParen,
    TwoParens,
}

impl<'de> Deserialize<'de> for ListNumberDelim {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &["DefaultDelim", "Period", "OneParen", "TwoParens"];
        let t = crate::de_tag(d, "ListNumberDelim", TAGS)?;
        Ok(match t.as_str() {
            "DefaultDelim" => ListNumberDelim::DefaultDelim,
            "Period" => ListNumberDelim::Period,
            "OneParen" => ListNumberDelim::OneParen,
            "TwoParens" => ListNumberDelim::TwoParens,
            _ => unreachable!(),
        })
    }
}

/// pandoc's `ShortCaption`.
pub type ShortCaption = Vec<Inline>;

/// pandoc's `Alignment`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(tag = "t")]
pub enum Alignment {
    AlignLeft,
    AlignRight,
    AlignCenter,
    AlignDefault,
}

impl<'de> Deserialize<'de> for Alignment {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &["AlignLeft", "AlignRight", "AlignCenter", "AlignDefault"];
        let t = crate::de_tag(d, "Alignment", TAGS)?;
        Ok(match t.as_str() {
            "AlignLeft" => Alignment::AlignLeft,
            "AlignRight" => Alignment::AlignRight,
            "AlignCenter" => Alignment::AlignCenter,
            "AlignDefault" => Alignment::AlignDefault,
            _ => unreachable!(),
        })
    }
}

/// pandoc's `ColWidth`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "t", content = "c")]
pub enum ColWidth {
    ColWidth(f64),
    ColWidthDefault,
}

impl<'de> Deserialize<'de> for ColWidth {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &["ColWidth", "ColWidthDefault"];
        struct V;
        impl<'de> de::Visitor<'de> for V {
            type Value = ColWidth;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("a ColWidth: {\"t\": ..., \"c\": ...}")
            }
            fn visit_map<A: de::MapAccess<'de>>(self, mut map: A) -> Result<ColWidth, A::Error> {
                let mut tag: Option<String> = None;
                let mut value: Option<ColWidth> = None;
                let mut early: Option<serde_json::Value> = None;
                while let Some(key) = map.next_key::<String>()? {
                    if key == "t" {
                        let t: String = map.next_value()?;
                        if !TAGS.contains(&t.as_str()) {
                            return Err(de::Error::unknown_variant(&t, TAGS));
                        }
                        value = match early.take() {
                            Some(c) => Some(from_value(&t, c)?),
                            None => unit(&t),
                        };
                        tag = Some(t);
                    } else if key == "c" {
                        match tag.as_deref() {
                            None => early = Some(map.next_value()?),
                            Some(t) => {
                                value = Some(match t {
                                    "ColWidth" => ColWidth::ColWidth(map.next_value()?),
                                    "ColWidthDefault" => {
                                        map.next_value::<de::IgnoredAny>()?;
                                        ColWidth::ColWidthDefault
                                    }
                                    _ => unreachable!(),
                                })
                            }
                        }
                    } else {
                        map.next_value::<de::IgnoredAny>()?;
                    }
                }
                match (tag, value) {
                    (_, Some(v)) => Ok(v),
                    (None, _) => Err(de::Error::missing_field("t")),
                    (Some(_), None) => Err(de::Error::missing_field("c")),
                }
            }
        }
        // "c" before "t" (not pandoc's order): decode it once "t" is known
        fn from_value<E: de::Error>(t: &str, c: serde_json::Value) -> Result<ColWidth, E> {
            fn json<T: de::DeserializeOwned, E: de::Error>(c: serde_json::Value) -> Result<T, E> {
                serde_path_to_error::deserialize(c).map_err(|e| {
                    let p = e.path().to_string();
                    let at = match p.as_str() {
                        "." => "c".to_string(),
                        p if p.starts_with('[') => format!("c{p}"),
                        p => format!("c.{p}"),
                    };
                    E::custom(format!("{at}: {}", e.inner()))
                })
            }
            Ok(match t {
                "ColWidth" => ColWidth::ColWidth(json(c)?),
                "ColWidthDefault" => ColWidth::ColWidthDefault,
                _ => unreachable!(),
            })
        }
        fn unit(t: &str) -> Option<ColWidth> {
            match t {
                "ColWidthDefault" => Some(ColWidth::ColWidthDefault),
                _ => None,
            }
        }
        d.deserialize_map(V)
    }
}

/// pandoc's `Row`.
#[derive(Debug, Clone, PartialEq)]
pub struct Row {
    pub attr: Attr,
    pub cells: Vec<Cell>,
}

impl Default for Row {
    fn default() -> Self {
        Row {
            attr: Attr::default(),
            cells: Vec::new(),
        }
    }
}

impl Serialize for Row {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (&self.attr, &self.cells).serialize(s)
    }
}

impl<'de> Deserialize<'de> for Row {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, cells) = <(Attr, Vec<Cell>)>::deserialize(d)?;
        Ok(Row { attr, cells })
    }
}

/// pandoc's `RowHeadColumns`.
pub type RowHeadColumns = i64;

/// pandoc's `CitationMode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(tag = "t")]
pub enum CitationMode {
    AuthorInText,
    SuppressAuthor,
    NormalCitation,
}

impl<'de> Deserialize<'de> for CitationMode {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        const TAGS: &[&str] = &["AuthorInText", "SuppressAuthor", "NormalCitation"];
        let t = crate::de_tag(d, "CitationMode", TAGS)?;
        Ok(match t.as_str() {
            "AuthorInText" => CitationMode::AuthorInText,
            "SuppressAuthor" => CitationMode::SuppressAuthor,
            "NormalCitation" => CitationMode::NormalCitation,
            _ => unreachable!(),
        })
    }
}

/// pandoc's `Cell`.
#[derive(Debug, Clone, PartialEq)]
pub struct Cell {
    pub attr: Attr,
    pub alignment: Alignment,
    pub row_span: RowSpan,
    pub col_span: ColSpan,
    pub content: Vec<Block>,
}

impl Default for Cell {
    fn default() -> Self {
        Cell {
            attr: Attr::default(),
            alignment: Alignment::AlignDefault,
            row_span: 1,
            col_span: 1,
            content: Vec::new(),
        }
    }
}

impl Serialize for Cell {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        (
            &self.attr,
            &self.alignment,
            &self.row_span,
            &self.col_span,
            &self.content,
        )
            .serialize(s)
    }
}

impl<'de> Deserialize<'de> for Cell {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let (attr, alignment, row_span, col_span, content) =
            <(Attr, Alignment, RowSpan, ColSpan, Vec<Block>)>::deserialize(d)?;
        Ok(Cell {
            attr,
            alignment,
            row_span,
            col_span,
            content,
        })
    }
}

/// pandoc's `RowSpan`.
pub type RowSpan = i64;

/// pandoc's `ColSpan`.
pub type ColSpan = i64;

/// A visitor over a document, changing it in place.
///
/// Each method's default visits the node's children (`walk_*`). Override
/// the ones for the nodes to change; call the `walk_*` function in an
/// override to visit the children too (before changing the node: bottom-up;
/// after: top-down).
///
/// ```
/// use pandom::{Inline, VisitMut, walk_inline};
///
/// struct Upper;
/// impl VisitMut for Upper {
///     fn visit_inline(&mut self, x: &mut Inline) {
///         walk_inline(self, x);
///         if let Inline::Str(s) = x {
///             *s = s.to_uppercase();
///         }
///     }
/// }
/// ```
pub trait VisitMut {
    fn visit_pandoc(&mut self, x: &mut Pandoc) {
        walk_pandoc(self, x)
    }
    fn visit_block(&mut self, x: &mut Block) {
        walk_block(self, x)
    }
    fn visit_meta_value(&mut self, x: &mut MetaValue) {
        walk_meta_value(self, x)
    }
    fn visit_inline(&mut self, x: &mut Inline) {
        walk_inline(self, x)
    }
    fn visit_attr(&mut self, x: &mut Attr) {
        walk_attr(self, x)
    }
    fn visit_list_attributes(&mut self, x: &mut ListAttributes) {
        walk_list_attributes(self, x)
    }
    fn visit_caption(&mut self, x: &mut Caption) {
        walk_caption(self, x)
    }
    fn visit_col_spec(&mut self, x: &mut ColSpec) {
        walk_col_spec(self, x)
    }
    fn visit_table_head(&mut self, x: &mut TableHead) {
        walk_table_head(self, x)
    }
    fn visit_table_body(&mut self, x: &mut TableBody) {
        walk_table_body(self, x)
    }
    fn visit_table_foot(&mut self, x: &mut TableFoot) {
        walk_table_foot(self, x)
    }
    fn visit_citation(&mut self, x: &mut Citation) {
        walk_citation(self, x)
    }
    fn visit_target(&mut self, x: &mut Target) {
        walk_target(self, x)
    }
    fn visit_col_width(&mut self, x: &mut ColWidth) {
        walk_col_width(self, x)
    }
    fn visit_row(&mut self, x: &mut Row) {
        walk_row(self, x)
    }
    fn visit_cell(&mut self, x: &mut Cell) {
        walk_cell(self, x)
    }
    /// The Blocks of one list, e.g. to splice or remove some.
    fn visit_blocks(&mut self, xs: &mut Vec<Block>) {
        walk_blocks(self, xs)
    }
    /// The Inlines of one list, e.g. to splice or remove some.
    fn visit_inlines(&mut self, xs: &mut Vec<Inline>) {
        walk_inlines(self, xs)
    }
    /// The MetaValues of one list, e.g. to splice or remove some.
    fn visit_meta_values(&mut self, xs: &mut Vec<MetaValue>) {
        walk_meta_values(self, xs)
    }
}

/// Visits each Block of a list.
pub fn walk_blocks<V: VisitMut + ?Sized>(v: &mut V, xs: &mut Vec<Block>) {
    for x in xs.iter_mut() {
        v.visit_block(x);
    }
}

/// Visits each Inline of a list.
pub fn walk_inlines<V: VisitMut + ?Sized>(v: &mut V, xs: &mut Vec<Inline>) {
    for x in xs.iter_mut() {
        v.visit_inline(x);
    }
}

/// Visits each MetaValue of a list.
pub fn walk_meta_values<V: VisitMut + ?Sized>(v: &mut V, xs: &mut Vec<MetaValue>) {
    for x in xs.iter_mut() {
        v.visit_meta_value(x);
    }
}

/// Visits the children of a Pandoc.
#[allow(unused_variables)]
pub fn walk_pandoc<V: VisitMut + ?Sized>(v: &mut V, x: &mut Pandoc) {
    for x0 in (&mut x.meta).values_mut() {
        v.visit_meta_value(x0);
    }
    v.visit_blocks(&mut x.blocks);
}

/// Visits the children of a Block.
#[allow(unused_variables)]
pub fn walk_block<V: VisitMut + ?Sized>(v: &mut V, x: &mut Block) {
    match x {
        Block::Plain(y) => {
            v.visit_inlines(y);
        }
        Block::Para(y) => {
            v.visit_inlines(y);
        }
        Block::LineBlock(y) => {
            for x0 in (y).iter_mut() {
                v.visit_inlines(x0);
            }
        }
        Block::CodeBlock(y) => {
            v.visit_attr(&mut y.attr);
        }
        Block::BlockQuote(y) => {
            v.visit_blocks(y);
        }
        Block::OrderedList(y) => {
            v.visit_list_attributes(&mut y.list_attributes);
            for x0 in (&mut y.content).iter_mut() {
                v.visit_blocks(x0);
            }
        }
        Block::BulletList(y) => {
            for x0 in (y).iter_mut() {
                v.visit_blocks(x0);
            }
        }
        Block::DefinitionList(y) => {
            for x0 in (y).iter_mut() {
                v.visit_inlines(&mut (x0).0);
                for x2 in (&mut (x0).1).iter_mut() {
                    v.visit_blocks(x2);
                }
            }
        }
        Block::Header(y) => {
            v.visit_attr(&mut y.attr);
            v.visit_inlines(&mut y.content);
        }
        Block::Table(y) => {
            v.visit_attr(&mut y.attr);
            v.visit_caption(&mut y.caption);
            for x0 in (&mut y.col_specs).iter_mut() {
                v.visit_col_spec(x0);
            }
            v.visit_table_head(&mut y.head);
            for x0 in (&mut y.bodies).iter_mut() {
                v.visit_table_body(x0);
            }
            v.visit_table_foot(&mut y.foot);
        }
        Block::Figure(y) => {
            v.visit_attr(&mut y.attr);
            v.visit_caption(&mut y.caption);
            v.visit_blocks(&mut y.content);
        }
        Block::Div(y) => {
            v.visit_attr(&mut y.attr);
            v.visit_blocks(&mut y.content);
        }
        _ => {}
    }
}

/// Visits the children of a MetaValue.
#[allow(unused_variables)]
pub fn walk_meta_value<V: VisitMut + ?Sized>(v: &mut V, x: &mut MetaValue) {
    match x {
        MetaValue::MetaMap(y) => {
            for x0 in (y).values_mut() {
                v.visit_meta_value(x0);
            }
        }
        MetaValue::MetaList(y) => {
            v.visit_meta_values(y);
        }
        MetaValue::MetaInlines(y) => {
            v.visit_inlines(y);
        }
        MetaValue::MetaBlocks(y) => {
            v.visit_blocks(y);
        }
        _ => {}
    }
}

/// Visits the children of a Inline.
#[allow(unused_variables)]
pub fn walk_inline<V: VisitMut + ?Sized>(v: &mut V, x: &mut Inline) {
    match x {
        Inline::Emph(y) => {
            v.visit_inlines(y);
        }
        Inline::Underline(y) => {
            v.visit_inlines(y);
        }
        Inline::Strong(y) => {
            v.visit_inlines(y);
        }
        Inline::Strikeout(y) => {
            v.visit_inlines(y);
        }
        Inline::Superscript(y) => {
            v.visit_inlines(y);
        }
        Inline::Subscript(y) => {
            v.visit_inlines(y);
        }
        Inline::SmallCaps(y) => {
            v.visit_inlines(y);
        }
        Inline::Quoted(y) => {
            v.visit_inlines(&mut y.content);
        }
        Inline::Cite(y) => {
            for x0 in (&mut y.citations).iter_mut() {
                v.visit_citation(x0);
            }
            v.visit_inlines(&mut y.content);
        }
        Inline::Code(y) => {
            v.visit_attr(&mut y.attr);
        }
        Inline::Link(y) => {
            v.visit_attr(&mut y.attr);
            v.visit_inlines(&mut y.content);
            v.visit_target(&mut y.target);
        }
        Inline::Image(y) => {
            v.visit_attr(&mut y.attr);
            v.visit_inlines(&mut y.content);
            v.visit_target(&mut y.target);
        }
        Inline::Note(y) => {
            v.visit_blocks(y);
        }
        Inline::Span(y) => {
            v.visit_attr(&mut y.attr);
            v.visit_inlines(&mut y.content);
        }
        _ => {}
    }
}

/// Visits the children of a Attr.
#[allow(unused_variables)]
pub fn walk_attr<V: VisitMut + ?Sized>(v: &mut V, x: &mut Attr) {}

/// Visits the children of a ListAttributes.
#[allow(unused_variables)]
pub fn walk_list_attributes<V: VisitMut + ?Sized>(v: &mut V, x: &mut ListAttributes) {}

/// Visits the children of a Caption.
#[allow(unused_variables)]
pub fn walk_caption<V: VisitMut + ?Sized>(v: &mut V, x: &mut Caption) {
    if let Some(x0) = (&mut x.short).as_mut() {
        v.visit_inlines(x0);
    }
    v.visit_blocks(&mut x.content);
}

/// Visits the children of a ColSpec.
#[allow(unused_variables)]
pub fn walk_col_spec<V: VisitMut + ?Sized>(v: &mut V, x: &mut ColSpec) {
    v.visit_col_width(&mut x.width);
}

/// Visits the children of a TableHead.
#[allow(unused_variables)]
pub fn walk_table_head<V: VisitMut + ?Sized>(v: &mut V, x: &mut TableHead) {
    v.visit_attr(&mut x.attr);
    for x0 in (&mut x.rows).iter_mut() {
        v.visit_row(x0);
    }
}

/// Visits the children of a TableBody.
#[allow(unused_variables)]
pub fn walk_table_body<V: VisitMut + ?Sized>(v: &mut V, x: &mut TableBody) {
    v.visit_attr(&mut x.attr);
    for x0 in (&mut x.head).iter_mut() {
        v.visit_row(x0);
    }
    for x0 in (&mut x.body).iter_mut() {
        v.visit_row(x0);
    }
}

/// Visits the children of a TableFoot.
#[allow(unused_variables)]
pub fn walk_table_foot<V: VisitMut + ?Sized>(v: &mut V, x: &mut TableFoot) {
    v.visit_attr(&mut x.attr);
    for x0 in (&mut x.rows).iter_mut() {
        v.visit_row(x0);
    }
}

/// Visits the children of a Citation.
#[allow(unused_variables)]
pub fn walk_citation<V: VisitMut + ?Sized>(v: &mut V, x: &mut Citation) {
    v.visit_inlines(&mut x.prefix);
    v.visit_inlines(&mut x.suffix);
}

/// Visits the children of a Target.
#[allow(unused_variables)]
pub fn walk_target<V: VisitMut + ?Sized>(v: &mut V, x: &mut Target) {}

/// Visits the children of a ColWidth.
#[allow(unused_variables)]
pub fn walk_col_width<V: VisitMut + ?Sized>(v: &mut V, x: &mut ColWidth) {}

/// Visits the children of a Row.
#[allow(unused_variables)]
pub fn walk_row<V: VisitMut + ?Sized>(v: &mut V, x: &mut Row) {
    v.visit_attr(&mut x.attr);
    for x0 in (&mut x.cells).iter_mut() {
        v.visit_cell(x0);
    }
}

/// Visits the children of a Cell.
#[allow(unused_variables)]
pub fn walk_cell<V: VisitMut + ?Sized>(v: &mut V, x: &mut Cell) {
    v.visit_attr(&mut x.attr);
    v.visit_blocks(&mut x.content);
}
