# GENERATED by tools/gen_python.py from schema/pandoc-ast.json
# (pandoc-api-version 1.23.1.2). Do not edit; regenerate instead.
"""pandoc's AST types: declarations only.

One class per constructor, a subclass of its type's class (``Header`` of
``Block``), and one per product type (``Attr``, ``Citation``, ...). Fields are
in pandoc-types' order. How the classes behave is in ``_core``.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import TYPE_CHECKING, TypeAlias

from ._core import Enum, Node, finalize
from ._core import flat as _flat
from ._core import init as _init

PANDOC_API_VERSION = (1, 23, 1, 2)


class QuoteType(Enum):
    """pandoc's ``QuoteType``."""

    SingleQuote = "SingleQuote"
    DoubleQuote = "DoubleQuote"


class MathType(Enum):
    """pandoc's ``MathType``."""

    DisplayMath = "DisplayMath"
    InlineMath = "InlineMath"


class ListNumberStyle(Enum):
    """pandoc's ``ListNumberStyle``."""

    DefaultStyle = "DefaultStyle"
    Example = "Example"
    Decimal = "Decimal"
    LowerRoman = "LowerRoman"
    UpperRoman = "UpperRoman"
    LowerAlpha = "LowerAlpha"
    UpperAlpha = "UpperAlpha"


class ListNumberDelim(Enum):
    """pandoc's ``ListNumberDelim``."""

    DefaultDelim = "DefaultDelim"
    Period = "Period"
    OneParen = "OneParen"
    TwoParens = "TwoParens"


class Alignment(Enum):
    """pandoc's ``Alignment``."""

    AlignLeft = "AlignLeft"
    AlignRight = "AlignRight"
    AlignCenter = "AlignCenter"
    AlignDefault = "AlignDefault"


class CitationMode(Enum):
    """pandoc's ``CitationMode``."""

    AuthorInText = "AuthorInText"
    SuppressAuthor = "SuppressAuthor"
    NormalCitation = "NormalCitation"


class Pandoc(Node):
    """pandoc's ``Pandoc``."""

    __slots__ = (
        "meta",
        "blocks",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "root"
    _keys = {"meta": "meta", "blocks": "blocks"}
    _variadic = "blocks"
    _defaults = {"meta": {}, "blocks": []}

    meta: Meta
    blocks: list[Block]

    def __init__(
        self,
        *blocks: Block | str,
        meta: Mapping[str, MetaValue] | None = None,
    ) -> None:
        _init(self, {"meta": meta, "blocks": blocks})


class Block(Node):
    """Any of pandoc's ``Block`` constructors."""

    __slots__ = ()
    _kind = "sum"


class Plain(Block):
    """pandoc's ``Plain``, a Block."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class Para(Block):
    """pandoc's ``Para``, a Block."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class LineBlock(Block):
    """pandoc's ``LineBlock``, a Block."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[list[Inline]]

    def __init__(self, *content: Iterable[Inline | str] | str) -> None:
        _init(self, {"content": content})


class CodeBlock(Block):
    """pandoc's ``CodeBlock``, a Block."""

    __slots__ = (
        "attr",
        "text",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []]}
    _positional = ("text",)

    attr: Attr
    text: str

    def __init__(
        self,
        text: str,
        *,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "CodeBlock",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "text": text})


class RawBlock(Block):
    """pandoc's ``RawBlock``, a Block."""

    __slots__ = (
        "format",
        "text",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _positional = ("format", "text")

    format: Format
    text: str

    def __init__(self, format: Format, text: str) -> None:
        _init(self, {"format": format, "text": text})


class BlockQuote(Block):
    """pandoc's ``BlockQuote``, a Block."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Block]

    def __init__(self, *content: Block | str) -> None:
        _init(self, {"content": content})


class OrderedList(Block):
    """pandoc's ``OrderedList``, a Block."""

    __slots__ = (
        "list_attributes",
        "content",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _flatten = ("list_attributes",)
    _defaults = {
        "list_attributes": [1, {"t": "DefaultStyle"}, {"t": "DefaultDelim"}],
        "content": [],
    }

    list_attributes: ListAttributes
    content: list[list[Block]]

    def __init__(
        self,
        *content: Iterable[Block | str] | str,
        list_attributes: ListAttributes | None = None,
        start: int = 1,
        style: ListNumberStyle = ListNumberStyle.DefaultStyle,
        delimiter: ListNumberDelim = ListNumberDelim.DefaultDelim,
    ) -> None:
        list_attributes = _flat(
            ListAttributes,
            "OrderedList",
            "list_attributes",
            list_attributes,
            {"start": start, "style": style, "delimiter": delimiter},
        )
        _init(self, {"list_attributes": list_attributes, "content": content})


class BulletList(Block):
    """pandoc's ``BulletList``, a Block."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[list[Block]]

    def __init__(self, *content: Iterable[Block | str] | str) -> None:
        _init(self, {"content": content})


class DefinitionList(Block):
    """pandoc's ``DefinitionList``, a Block."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[tuple[list[Inline], list[list[Block]]]]

    def __init__(
        self,
        *content: tuple[Iterable[Inline | str] | str, Iterable[Iterable[Block | str] | str]],
    ) -> None:
        _init(self, {"content": content})


class Header(Block):
    """pandoc's ``Header``, a Block."""

    __slots__ = (
        "level",
        "attr",
        "content",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "content": []}
    _positional = ("level",)

    level: int
    attr: Attr
    content: list[Inline]

    def __init__(
        self,
        level: int,
        *content: Inline | str,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "Header",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"level": level, "attr": attr, "content": content})


class HorizontalRule(Block):
    """pandoc's ``HorizontalRule``, a Block."""

    __slots__ = ()
    __match_args__ = __slots__
    _encoding = "none"


class Table(Block):
    """pandoc's ``Table``, a Block."""

    __slots__ = (
        "attr",
        "caption",
        "col_specs",
        "head",
        "bodies",
        "foot",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _flatten = ("attr",)
    _defaults = {
        "attr": ["", [], []],
        "caption": [None, []],
        "col_specs": [],
        "head": [["", [], []], []],
        "bodies": [],
        "foot": [["", [], []], []],
    }
    _positional = ("caption", "col_specs", "head", "bodies", "foot")

    attr: Attr
    caption: Caption
    col_specs: list[ColSpec]
    head: TableHead
    bodies: list[TableBody]
    foot: TableFoot

    def __init__(
        self,
        caption: Caption | None = None,
        col_specs: Iterable[ColSpec] = (),
        head: TableHead | None = None,
        bodies: Iterable[TableBody] = (),
        foot: TableFoot | None = None,
        *,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "Table",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(
            self,
            {
                "attr": attr,
                "caption": caption,
                "col_specs": col_specs,
                "head": head,
                "bodies": bodies,
                "foot": foot,
            },
        )


class Figure(Block):
    """pandoc's ``Figure``, a Block."""

    __slots__ = (
        "attr",
        "caption",
        "content",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "caption": [None, []], "content": []}

    attr: Attr
    caption: Caption
    content: list[Block]

    def __init__(
        self,
        *content: Block | str,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
        caption: Caption | None = None,
    ) -> None:
        attr = _flat(
            Attr,
            "Figure",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "caption": caption, "content": content})


class Div(Block):
    """pandoc's ``Div``, a Block."""

    __slots__ = (
        "attr",
        "content",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "content": []}

    attr: Attr
    content: list[Block]

    def __init__(
        self,
        *content: Block | str,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "Div",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "content": content})


class MetaValue(Node):
    """Any of pandoc's ``MetaValue`` constructors."""

    __slots__ = ()
    _kind = "sum"


class MetaMap(MetaValue):
    """pandoc's ``MetaMap``, a MetaValue."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _defaults = {"content": {}}
    _positional = ("content",)

    content: dict[str, MetaValue]

    def __init__(self, content: Mapping[str, MetaValue] | None = None) -> None:
        _init(self, {"content": content})


class MetaList(MetaValue):
    """pandoc's ``MetaList``, a MetaValue."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[MetaValue]

    def __init__(self, *content: MetaValue) -> None:
        _init(self, {"content": content})


class MetaBool(MetaValue):
    """pandoc's ``MetaBool``, a MetaValue."""

    __slots__ = ("value",)
    __match_args__ = __slots__
    _encoding = "value"
    _positional = ("value",)

    value: bool

    def __init__(self, value: bool) -> None:
        _init(self, {"value": value})


class MetaString(MetaValue):
    """pandoc's ``MetaString``, a MetaValue."""

    __slots__ = ("text",)
    __match_args__ = __slots__
    _encoding = "value"
    _positional = ("text",)

    text: str

    def __init__(self, text: str) -> None:
        _init(self, {"text": text})


class MetaInlines(MetaValue):
    """pandoc's ``MetaInlines``, a MetaValue."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class MetaBlocks(MetaValue):
    """pandoc's ``MetaBlocks``, a MetaValue."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Block]

    def __init__(self, *content: Block | str) -> None:
        _init(self, {"content": content})


class Inline(Node):
    """Any of pandoc's ``Inline`` constructors."""

    __slots__ = ()
    _kind = "sum"


class Str(Inline):
    """pandoc's ``Str``, a Inline."""

    __slots__ = ("text",)
    __match_args__ = __slots__
    _encoding = "value"
    _positional = ("text",)

    text: str

    def __init__(self, text: str) -> None:
        _init(self, {"text": text})


class Emph(Inline):
    """pandoc's ``Emph``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class Underline(Inline):
    """pandoc's ``Underline``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class Strong(Inline):
    """pandoc's ``Strong``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class Strikeout(Inline):
    """pandoc's ``Strikeout``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class Superscript(Inline):
    """pandoc's ``Superscript``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class Subscript(Inline):
    """pandoc's ``Subscript``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class SmallCaps(Inline):
    """pandoc's ``SmallCaps``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Inline]

    def __init__(self, *content: Inline | str) -> None:
        _init(self, {"content": content})


class Quoted(Inline):
    """pandoc's ``Quoted``, a Inline."""

    __slots__ = (
        "quote_type",
        "content",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _defaults = {"content": []}
    _positional = ("quote_type",)

    quote_type: QuoteType
    content: list[Inline]

    def __init__(self, quote_type: QuoteType, *content: Inline | str) -> None:
        _init(self, {"quote_type": quote_type, "content": content})


class Cite(Inline):
    """pandoc's ``Cite``, a Inline."""

    __slots__ = (
        "citations",
        "content",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _defaults = {"citations": [], "content": []}
    _positional = ("citations", "content")

    citations: list[Citation]
    content: list[Inline]

    def __init__(
        self,
        citations: Iterable[Citation] = (),
        content: Iterable[Inline | str] | str = (),
    ) -> None:
        _init(self, {"citations": citations, "content": content})


class Code(Inline):
    """pandoc's ``Code``, a Inline."""

    __slots__ = (
        "attr",
        "text",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []]}
    _positional = ("text",)

    attr: Attr
    text: str

    def __init__(
        self,
        text: str,
        *,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "Code",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "text": text})


class Space(Inline):
    """pandoc's ``Space``, a Inline."""

    __slots__ = ()
    __match_args__ = __slots__
    _encoding = "none"


class SoftBreak(Inline):
    """pandoc's ``SoftBreak``, a Inline."""

    __slots__ = ()
    __match_args__ = __slots__
    _encoding = "none"


class LineBreak(Inline):
    """pandoc's ``LineBreak``, a Inline."""

    __slots__ = ()
    __match_args__ = __slots__
    _encoding = "none"


class Math(Inline):
    """pandoc's ``Math``, a Inline."""

    __slots__ = (
        "math_type",
        "text",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _positional = ("math_type", "text")

    math_type: MathType
    text: str

    def __init__(self, math_type: MathType, text: str) -> None:
        _init(self, {"math_type": math_type, "text": text})


class RawInline(Inline):
    """pandoc's ``RawInline``, a Inline."""

    __slots__ = (
        "format",
        "text",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _positional = ("format", "text")

    format: Format
    text: str

    def __init__(self, format: Format, text: str) -> None:
        _init(self, {"format": format, "text": text})


class Link(Inline):
    """pandoc's ``Link``, a Inline."""

    __slots__ = (
        "attr",
        "content",
        "target",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _flatten = ("attr", "target")
    _defaults = {"attr": ["", [], []], "content": []}

    attr: Attr
    content: list[Inline]
    target: Target

    def __init__(
        self,
        *content: Inline | str,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
        target: Target | None = None,
        url: str | None = None,
        title: str = "",
    ) -> None:
        attr = _flat(
            Attr,
            "Link",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        target = _flat(Target, "Link", "target", target, {"url": url, "title": title})
        _init(self, {"attr": attr, "content": content, "target": target})


class Image(Inline):
    """pandoc's ``Image``, a Inline."""

    __slots__ = (
        "attr",
        "content",
        "target",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _flatten = ("attr", "target")
    _defaults = {"attr": ["", [], []], "content": []}

    attr: Attr
    content: list[Inline]
    target: Target

    def __init__(
        self,
        *content: Inline | str,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
        target: Target | None = None,
        url: str | None = None,
        title: str = "",
    ) -> None:
        attr = _flat(
            Attr,
            "Image",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        target = _flat(Target, "Image", "target", target, {"url": url, "title": title})
        _init(self, {"attr": attr, "content": content, "target": target})


class Note(Inline):
    """pandoc's ``Note``, a Inline."""

    __slots__ = ("content",)
    __match_args__ = __slots__
    _encoding = "value"
    _variadic = "content"
    _defaults = {"content": []}

    content: list[Block]

    def __init__(self, *content: Block | str) -> None:
        _init(self, {"content": content})


class Span(Inline):
    """pandoc's ``Span``, a Inline."""

    __slots__ = (
        "attr",
        "content",
    )
    __match_args__ = __slots__
    _encoding = "array"
    _variadic = "content"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "content": []}

    attr: Attr
    content: list[Inline]

    def __init__(
        self,
        *content: Inline | str,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "Span",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "content": content})


class Attr(Node):
    """pandoc's ``Attr``."""

    __slots__ = (
        "identifier",
        "classes",
        "attributes",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _defaults = {"identifier": "", "classes": [], "attributes": []}
    _positional = ("identifier", "classes", "attributes")

    identifier: str
    classes: list[str]
    attributes: list[tuple[str, str]]

    def __init__(
        self,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        _init(
            self,
            {
                "identifier": identifier,
                "classes": classes,
                "attributes": attributes,
            },
        )


class ListAttributes(Node):
    """pandoc's ``ListAttributes``."""

    __slots__ = (
        "start",
        "style",
        "delimiter",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _defaults = {"start": 1, "style": {"t": "DefaultStyle"}, "delimiter": {"t": "DefaultDelim"}}
    _positional = ("start", "style", "delimiter")

    start: int
    style: ListNumberStyle
    delimiter: ListNumberDelim

    def __init__(
        self,
        start: int = 1,
        style: ListNumberStyle = ListNumberStyle.DefaultStyle,
        delimiter: ListNumberDelim = ListNumberDelim.DefaultDelim,
    ) -> None:
        _init(self, {"start": start, "style": style, "delimiter": delimiter})


class Caption(Node):
    """pandoc's ``Caption``."""

    __slots__ = (
        "short",
        "content",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _variadic = "content"
    _defaults = {"short": None, "content": []}

    short: ShortCaption | None
    content: list[Block]

    def __init__(
        self,
        *content: Block | str,
        short: Iterable[Inline | str] | str | None = None,
    ) -> None:
        _init(self, {"short": short, "content": content})


class ColSpec(Node):
    """pandoc's ``ColSpec``."""

    __slots__ = (
        "alignment",
        "width",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _defaults = {"alignment": {"t": "AlignDefault"}, "width": {"t": "ColWidthDefault"}}
    _positional = ("alignment", "width")

    alignment: Alignment
    width: ColWidthBase

    def __init__(
        self,
        alignment: Alignment = Alignment.AlignDefault,
        width: ColWidthBase | None = None,
    ) -> None:
        _init(self, {"alignment": alignment, "width": width})


class TableHead(Node):
    """pandoc's ``TableHead``."""

    __slots__ = (
        "attr",
        "rows",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _variadic = "rows"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "rows": []}

    attr: Attr
    rows: list[Row]

    def __init__(
        self,
        *rows: Row,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "TableHead",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "rows": rows})


class TableBody(Node):
    """pandoc's ``TableBody``."""

    __slots__ = (
        "attr",
        "row_head_columns",
        "head",
        "body",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "row_head_columns": 0, "head": [], "body": []}
    _positional = ("row_head_columns", "head", "body")

    attr: Attr
    row_head_columns: RowHeadColumns
    head: list[Row]
    body: list[Row]

    def __init__(
        self,
        row_head_columns: RowHeadColumns = 0,
        head: Iterable[Row] = (),
        body: Iterable[Row] = (),
        *,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "TableBody",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(
            self,
            {
                "attr": attr,
                "row_head_columns": row_head_columns,
                "head": head,
                "body": body,
            },
        )


class TableFoot(Node):
    """pandoc's ``TableFoot``."""

    __slots__ = (
        "attr",
        "rows",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _variadic = "rows"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "rows": []}

    attr: Attr
    rows: list[Row]

    def __init__(
        self,
        *rows: Row,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "TableFoot",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "rows": rows})


class Citation(Node):
    """pandoc's ``Citation``."""

    __slots__ = (
        "id",
        "prefix",
        "suffix",
        "mode",
        "note_num",
        "hash",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "object"
    _keys = {
        "id": "citationId",
        "prefix": "citationPrefix",
        "suffix": "citationSuffix",
        "mode": "citationMode",
        "note_num": "citationNoteNum",
        "hash": "citationHash",
    }
    _defaults = {
        "prefix": [],
        "suffix": [],
        "mode": {"t": "NormalCitation"},
        "note_num": 0,
        "hash": 0,
    }
    _positional = ("id", "prefix", "suffix", "mode", "note_num", "hash")

    id: str
    prefix: list[Inline]
    suffix: list[Inline]
    mode: CitationMode
    note_num: int
    hash: int

    def __init__(
        self,
        id: str,
        prefix: Iterable[Inline | str] | str = (),
        suffix: Iterable[Inline | str] | str = (),
        mode: CitationMode = CitationMode.NormalCitation,
        note_num: int = 0,
        hash: int = 0,
    ) -> None:
        _init(
            self,
            {
                "id": id,
                "prefix": prefix,
                "suffix": suffix,
                "mode": mode,
                "note_num": note_num,
                "hash": hash,
            },
        )


class Target(Node):
    """pandoc's ``Target``."""

    __slots__ = (
        "url",
        "title",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _defaults = {"title": ""}
    _positional = ("url", "title")

    url: str
    title: str

    def __init__(self, url: str, title: str = "") -> None:
        _init(self, {"url": url, "title": title})


class ColWidthBase(Node):
    """Any of pandoc's ``ColWidth`` constructors."""

    __slots__ = ()
    _kind = "sum"


class ColWidth(ColWidthBase):
    """pandoc's ``ColWidth``, a ColWidth."""

    __slots__ = ("width",)
    __match_args__ = __slots__
    _encoding = "value"
    _positional = ("width",)

    width: float

    def __init__(self, width: float) -> None:
        _init(self, {"width": width})


class ColWidthDefault(ColWidthBase):
    """pandoc's ``ColWidthDefault``, a ColWidth."""

    __slots__ = ()
    __match_args__ = __slots__
    _encoding = "none"


class Row(Node):
    """pandoc's ``Row``."""

    __slots__ = (
        "attr",
        "cells",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _variadic = "cells"
    _flatten = ("attr",)
    _defaults = {"attr": ["", [], []], "cells": []}

    attr: Attr
    cells: list[Cell]

    def __init__(
        self,
        *cells: Cell,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
    ) -> None:
        attr = _flat(
            Attr,
            "Row",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(self, {"attr": attr, "cells": cells})


class Cell(Node):
    """pandoc's ``Cell``."""

    __slots__ = (
        "attr",
        "alignment",
        "row_span",
        "col_span",
        "content",
    )
    __match_args__ = __slots__
    _kind = "product"
    _encoding = "array"
    _variadic = "content"
    _flatten = ("attr",)
    _defaults = {
        "attr": ["", [], []],
        "alignment": {"t": "AlignDefault"},
        "row_span": 1,
        "col_span": 1,
        "content": [],
    }

    attr: Attr
    alignment: Alignment
    row_span: RowSpan
    col_span: ColSpan
    content: list[Block]

    def __init__(
        self,
        *content: Block | str,
        attr: Attr | None = None,
        identifier: str = "",
        classes: Iterable[str] = (),
        attributes: Iterable[tuple[str, str]] | Mapping[str, str] = (),
        alignment: Alignment = Alignment.AlignDefault,
        row_span: RowSpan = 1,
        col_span: ColSpan = 1,
    ) -> None:
        attr = _flat(
            Attr,
            "Cell",
            "attr",
            attr,
            {"identifier": identifier, "classes": classes, "attributes": attributes},
        )
        _init(
            self,
            {
                "attr": attr,
                "alignment": alignment,
                "row_span": row_span,
                "col_span": col_span,
                "content": content,
            },
        )


# pandoc-types' newtypes and type synonyms
Meta: TypeAlias = dict[str, MetaValue]
Format: TypeAlias = str
ShortCaption: TypeAlias = list[Inline]
RowHeadColumns: TypeAlias = int
RowSpan: TypeAlias = int
ColSpan: TypeAlias = int

# How Filter.on types a filter's functions, for type checkers only: a
# function for a kind of node takes it (and optionally a Context) and
# returns None, a node of the same family, or a list of them.
if TYPE_CHECKING:
    from collections.abc import Callable, Sequence
    from typing import Any, TypeVar, overload

    from ._walk import Context

    _F = TypeVar("_F", bound=Callable[..., Any])
    _Node = TypeVar("_Node", bound=Node)
    _Block = TypeVar("_Block", bound=Block)
    _MetaValue = TypeVar("_MetaValue", bound=MetaValue)
    _Inline = TypeVar("_Inline", bound=Inline)
    _ColWidthBase = TypeVar("_ColWidthBase", bound=ColWidthBase)

    @overload
    def _typed_on(
        self: Any, type: type[_Block], /, *types: type[_Block]
    ) -> Callable[
        [
            Callable[[_Block], Block | Sequence[Block] | None]
            | Callable[[_Block, Context], Block | Sequence[Block] | None]
        ],
        Callable[..., Any],
    ]: ...

    @overload
    def _typed_on(
        self: Any, type: type[_MetaValue], /, *types: type[_MetaValue]
    ) -> Callable[
        [
            Callable[[_MetaValue], MetaValue | Sequence[MetaValue] | None]
            | Callable[[_MetaValue, Context], MetaValue | Sequence[MetaValue] | None]
        ],
        Callable[..., Any],
    ]: ...

    @overload
    def _typed_on(
        self: Any, type: type[_Inline], /, *types: type[_Inline]
    ) -> Callable[
        [
            Callable[[_Inline], Inline | Sequence[Inline] | None]
            | Callable[[_Inline, Context], Inline | Sequence[Inline] | None]
        ],
        Callable[..., Any],
    ]: ...

    @overload
    def _typed_on(
        self: Any, type: type[_ColWidthBase], /, *types: type[_ColWidthBase]
    ) -> Callable[
        [
            Callable[[_ColWidthBase], ColWidthBase | Sequence[ColWidthBase] | None]
            | Callable[[_ColWidthBase, Context], ColWidthBase | Sequence[ColWidthBase] | None]
        ],
        Callable[..., Any],
    ]: ...

    @overload
    def _typed_on(
        self: Any, type: type[_Node], /, *types: type[_Node]
    ) -> Callable[
        [
            Callable[[_Node], _Node | Sequence[_Node] | None]
            | Callable[[_Node, Context], _Node | Sequence[_Node] | None]
        ],
        Callable[..., Any],
    ]: ...

    @overload
    def _typed_on(self: Any, *types: type[Node]) -> Callable[[_F], _F]: ...

    def _typed_on(self: Any, *types: Any) -> Any: ...


__all__ = [
    "PANDOC_API_VERSION",
    "QuoteType",
    "MathType",
    "ListNumberStyle",
    "ListNumberDelim",
    "Alignment",
    "CitationMode",
    "Pandoc",
    "Block",
    "Plain",
    "Para",
    "LineBlock",
    "CodeBlock",
    "RawBlock",
    "BlockQuote",
    "OrderedList",
    "BulletList",
    "DefinitionList",
    "Header",
    "HorizontalRule",
    "Table",
    "Figure",
    "Div",
    "MetaValue",
    "MetaMap",
    "MetaList",
    "MetaBool",
    "MetaString",
    "MetaInlines",
    "MetaBlocks",
    "Inline",
    "Str",
    "Emph",
    "Underline",
    "Strong",
    "Strikeout",
    "Superscript",
    "Subscript",
    "SmallCaps",
    "Quoted",
    "Cite",
    "Code",
    "Space",
    "SoftBreak",
    "LineBreak",
    "Math",
    "RawInline",
    "Link",
    "Image",
    "Note",
    "Span",
    "Attr",
    "ListAttributes",
    "Caption",
    "ColSpec",
    "TableHead",
    "TableBody",
    "TableFoot",
    "Citation",
    "Target",
    "ColWidthBase",
    "ColWidth",
    "ColWidthDefault",
    "Row",
    "Cell",
    "Meta",
    "Format",
    "ShortCaption",
    "RowHeadColumns",
    "RowSpan",
    "ColSpan",
]

finalize(globals(), PANDOC_API_VERSION)
